In [1]:
import pandas as pd

path = '../data/Movies/tmdb_5000_movies.csv'



df = pd.read_csv(path)


In [2]:
df.shape

(4803, 20)

In [3]:
df.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [4]:
df_movies = df[['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']]

In [5]:
df_movies

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                                 genres  vote_average  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   
...                                                 ...           ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           6.6   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...           5.9   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...           7.0   
4801                                                 []           5.7   
4802                [{"id": 99, "name": "Documentary"}]           6.3   

      vote_count  popularity  \
0          11800  150.437577   
1           4500  139.082615   
2           4466  107.376788   
3           9106  112.312950   
4           2124   43.926995   
...          ...         ...   
4798         238   14.269792   
4799           5    0.642552   
4800           6    1.444476   
4801           7    0.857008   
4802          16    1.929883   

                                               keywords  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4     [{"id": 818, "name": "based on novel"}, {"id":...   
...                                                 ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...   
4799                                                 []   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...   
4801                                                 []   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4798  El Mariachi just wants to play his guitar and ...  
4799  A newlywed couple's honeymoon is upended by th...  
4800  "Signed, Sealed, Delivered" introduces a dedic...  
4801  When ambitious New York attorney Sam is sent t...  
4802  Ever since the second grade when he first saw ...  

[4803 rows x 8 columns]

In [6]:
df_movies.describe()

id  vote_average    vote_count   popularity
count    4803.000000   4803.000000   4803.000000  4803.000000
mean    57165.484281      6.092172    690.217989    21.492301
std     88694.614033      1.194612   1234.585891    31.816650
min         5.000000      0.000000      0.000000     0.000000
25%      9014.500000      5.600000     54.000000     4.668070
50%     14629.000000      6.200000    235.000000    12.921594
75%     58610.500000      6.800000    737.000000    28.313505
max    459488.000000     10.000000  13752.000000   875.581305

In [7]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            4803 non-null   int64  
 1   title         4803 non-null   object 
 2   genres        4803 non-null   object 
 3   vote_average  4803 non-null   float64
 4   vote_count    4803 non-null   int64  
 5   popularity    4803 non-null   float64
 6   keywords      4803 non-null   object 
 7   overview      4800 non-null   object 
dtypes: float64(2), int64(2), object(4)
memory usage: 300.3+ KB


In [8]:
df_movies[['genres', 'keywords']][:3]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...

In [17]:
pd.set_option('max_colwidth', 100)
df_movies[['genres', 'keywords']][:3]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...   
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]   
2         [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]   

                                                                                              keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic is...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name": "based on novel"}, {"id": 4289, "name": "secret...

In [18]:
pd.reset_option('max_colwidth')
df_movies[['genres', 'keywords']][:3]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...

In [19]:
# 데이터 가공

In [39]:
str_dict = ' {"id":28, "name": "Action"}'
print(type(str_dict))
print(str_dict)

<class 'str'>
 {"id":28, "name": "Action"}


In [40]:
# 모든 데이터 출력
df_movies['genres']
# 1행만 출력, series 형식
df_movies['genres'][:1]
# 1행만 출력, str 형식
print(df_movies['genres'][:1][0])
# 문자열에 0번에 위치의 값
df_movies['genres'][:1][0][0]


[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]


{'id': 28, 'name': 'Action'}

In [41]:
#  >"df_movies['genres'][:1][0]" 이 
# 정보는 리스트 모양을 갖지만 실제 자료형은 str 형식이다. 
# 리스트에서 첫 번째 데이터인 {"id": 28, "name": "Action"} 이 
# 정보를 얻으려 df_movies['genres'][:1][0][0] 이렇게 진행했지만 결과는 str 형식이기
# 때문에 첫 번째 위치의 '['이 출력된 것이다.

In [46]:
from ast import literal_eval

#df_movies['genres'] = df_movies['genres'].apply(literal_eval)
print(type(df_movies['genres'][:1][0]))
df_movies['genres'][:1][0][0]


# 주석한 이유, 이미 리스트로 변환되었는데, 또 실행시켜서 오류 나는 것같음.
# genres 들을 리스트 형식으로 변환


<class 'list'>


{'id': 28, 'name': 'Action'}

In [47]:
df_movies['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [48]:
for genre in df_movies['genres'][0]:
    print(genre['name'])

Action
Adventure
Fantasy
Science Fiction


In [94]:
# df_movies['genres'] = df_movies['genres'].apply(lambda x : [y['name'] for y in x])
df_movies['genres'][2]

['Action', 'Adventure', 'Crime']

In [55]:
# 6. fearture 생성



In [72]:
'==='.join(df_movies['genres'][0])

'Action===Adventure===Fantasy===Science Fiction'

In [73]:
# df_movies['genres'][0] = df_movies['genres'][0].replace("===", " ")
# 오류남 ㅠㅠ

In [116]:
# df_movies['genres'][0]
# result_list=[]
# for i in df_movies['genres'][0]:
#     temp = i.replace("==="," ")
#     result_list.append(temp)

# 하면
# ['Action', 'Adventure', 'Fantasy', 'Science Fiction'] 다시 일케댐

In [117]:
df_movies['genres'][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [76]:
'==='.join(df_movies['genres'][0])

'Action===Adventure===Fantasy===Science Fiction'

In [83]:
df_movies['genres_literal'] = df_movies['genres'].apply(lambda x : (' ').join(x))

<ipython-input-83-79915ab1a189>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['genres_literal'] = df_movies['genres'].apply(lambda x : (' ').join(x))


In [84]:
df_movies['genres_literal'][0]

'Action Adventure Fantasy Science Fiction'

In [86]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(ngram_range=(1,2)).fit(df_movies['genres_literal'])
count_vect.vocabulary_

ModuleNotFoundError: No module named 'sklearn'

In [89]:
!pip install -U scikit-learn

You should consider upgrading via the 'c:\users\5-17\jupylab\scripts\python.exe -m pip install --upgrade pip' command.


In [108]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(ngram_range=(1,2)).fit(df_movies['genres_literal'])
#count_vect.vocabulary_

In [109]:
# CountVectorizer에서 ngram_range는 단어의 조합을 어떻게 처리할 것이냐를 정하는 것으로 다음과 같이 사용할 수 있다.
# ngram_range(min_n, max_n)
# min_n : 최소 단어 수
# max_n : 최대 단어수
# 최소 단어수에서 최대 단어 수까지 조합으로 count할 단어를 생성

#  단어가 너무 많으면 처리하는데 많은 시간이 소요되어 2개의 단어조합 까지만 사용한다.

In [111]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2)).fit(df_movies['genres_literal'])
#count_vect.vocabulary_

In [112]:
# min_df는 최소 빈도 수를 의미하며 0을 사용하면 모든 단어들의 조합을 사용하겠다는 의미이다. 
# 만약 100이 입력되면 100번 이하로 나타나는 조합은 배제하겠다는 의미이다.

In [113]:
genre_matrix = count_vect.fit_transform(df_movies['genres_literal'])
genre_matrix.shape

(4803, 276)

In [114]:
# 유사도 분석


In [115]:
from sklearn.metrics.pairwise import cosine_similarity

genre_similarity = cosine_similarity(genre_matrix, genre_matrix)
genre_similarity[:3]

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ]])

In [118]:
# 간단하게 유사도 측정을 했다. 총 4803개의 데이터가 존재하며 각 
# 데이터들의 유사도로 나타나기 때문에 영화를 찾기에는 어렵다. 
# 따라서 결과를 정렬된 index 정보로 출력해 볼 것이다.

In [120]:
genre_similarity_sorted_idx = genre_similarity.argsort()[:,::-1]
genre_similarity_sorted_idx[:3]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401]], dtype=int64)

In [121]:
# argsort()는 배열 정렬시 사용하는 함수로 기본은 오름차순으로 정렬된다.
# 하지만 우리가 필요한 정보는 유사도가 높은 정보순으로 정렬해야 함으로
# 내림차순으로 정렬하기 위해 [:,::-1]을 이용했다. 또한 출력 결과는 유사도가 
# 아닌 index인 것에 유의하자.
# 위의 정보에서 0번 영화와 가장 유사한 영화는 3493->813 순 인것을 알 수있다.

In [123]:
print(df_movies.iloc[0]['title'])
print(df_movies.iloc[3493]['title'])
print(df_movies.iloc[813]['title'])
print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")
df_movies.iloc[0]

Avatar
Morvern Callar
Superman
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ


id                                                            19995
title                                                        Avatar
genres                [Action, Adventure, Fantasy, Science Fiction]
vote_average                                                    7.2
vote_count                                                    11800
popularity                                               150.437577
keywords          [{"id": 1463, "name": "culture clash"}, {"id":...
overview          In the 22nd century, a paraplegic Marine is di...
genres_literal             Action Adventure Fantasy Science Fiction
Name: 0, dtype: object

In [124]:
# iloc를 이용하면 index의 정보를 얻을 수 있다. 
# 즉, 영화의 정보를 얻기 위해 iloc에 index 정보를 넣고 
# 그 중 title feature를 출력하여 추천 영화들을 얻을 수 있게 된다.

In [126]:
# 8. 영화 추천하기

# 제목을 입력하면 특정 영화 정보가 출력되도록 코딩하시오.

In [137]:
# df_movies['title']
# df_movies['title']=='Avatar'
df_movies[df_movies['title']=='Avatar']

# df_movies['title'].isin(['Avatar'])
# df_movies['title'].isin(['Avatar']) 랑 df_movies['title']=='Avatar' 같다

df_movies[df_movies['title'].isin(['Avatar'])]


id   title                                         genres  vote_average  \
0  19995  Avatar  [Action, Adventure, Fantasy, Science Fiction]           7.2   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction

In [141]:
movie_name = 'avatar'
movie_name.upper()
movie_name.lower()
df_movies[df_movies['title'].str.lower().isin([movie_name.lower()])]

id   title                                         genres  vote_average  \
0  19995  Avatar  [Action, Adventure, Fantasy, Science Fiction]           7.2   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction

In [142]:
# 사용자가 입력하는 정보는 대문자, 소문자를 구분하지 않고 사용하기 때문에 하나로 통일해야 검색이 가능하다. 
# upper 함수는 모든 문자를 대문자로 변환하며 lower 함수는 모든 문자를 소문자로 변환한다.

# 여기서는 사용자가 입력하는 문자를 소문자로 변환하기 위해 movie_name.lower()를 사용했다. 
# 또한 기존에 영화 제목 정보들은 series 형으로 되어 있어 문자열로 변환하기 위해
# str을 사용했으며 마찬가지로 lower함수를 통해 소문자로 통일하였다.

In [153]:
movie_name = 'superman'
title_movie = df_movies[df_movies['title'].str.lower().isin([movie_name.lower()])]
title_movie.index.values

array([813], dtype=int64)

In [154]:
genre_similarity_sorted_idx[:4, :10]

array([[   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420],
       [ 262,    1,  129,  199,  206,  208,   98, 2343, 2390,  379],
       [   2, 1740, 1542, 1082,  873, 1615,  969, 1058, 1073, 1076],
       [2195, 1850, 3316, 2218, 2435, 3073, 1503, 1470, 4230,  629]],
      dtype=int64)

In [155]:
# [:4, :10]은 행을 4개까지 열을 10개까지 출력하는 기능을 한다.

# 위의 결과를 보면 4개의 영화 정보에 대한 10개의 추천 영화 index를 반환한 결과이다.

In [156]:
genre_similarity_sorted_idx.shape

(4803, 4803)

In [157]:
genre_similarity_sorted_idx[0, :10]

array([   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420],
      dtype=int64)

In [158]:
# 위의 결과는 0번 영화에 대한 top10의 추천 영화정보이다.

In [163]:
movie_index = title_movie.index.values
movie_index
genre_similarity_sorted_idx[movie_index, :10]

array([[   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420]],
      dtype=int64)

In [164]:
df_movies.iloc[[   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420]]

# iloc 로 integer 로 인덱스 번호를 받아서 영화 정보를 보여줌

id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   
14     49521                               Man of Steel   
1296    9531                               Superman III   
1652   14164                       Dragonball Evolution   
419     8247                                     Jumper   
420    11253                Hellboy II: The Golden Army   

                                                 genres  vote_average  \
0         [Action, Adventure, Fantasy, Science Fiction]           7.2   
3494      [Action, Adventure, Fantasy, Science Fiction]           4.6   
813       [Action, Adventure, Fantasy, Science Fiction]           6.9   
870       [Action, Adventure, Fantasy, Science Fiction]           6.5   
46        [Action, Adventure, Fantasy, Science Fiction]           7.5   
14        [Action, Adventure, Fantasy, Science Fiction]           6.5   
1296  [Comedy, Action, Adventure, Fantasy, Science F...           5.3   
1652  [Action, Adventure, Fantasy, Science Fiction, ...           2.9   
419               [Adventure, Fantasy, Science Fiction]           5.9   
420               [Adventure, Fantasy, Science Fiction]           6.5   

      vote_count  popularity  \
0          11800  150.437577   
3494          17    1.478505   
813         1022   48.507081   
870          629   30.515175   
46          6032  118.078691   
14          6359   99.398009   
1296         490   22.164202   
1652         462   21.677732   
419         1799   21.218000   
420         1527   58.579760   

                                               keywords  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...   
3494  [{"id": 818, "name": "based on novel"}, {"id":...   
813   [{"id": 83, "name": "saving the world"}, {"id"...   
870   [{"id": 83, "name": "saving the world"}, {"id"...   
46    [{"id": 1228, "name": "1970s"}, {"id": 1852, "...   
14    [{"id": 83, "name": "saving the world"}, {"id"...   
1296  [{"id": 83, "name": "saving the world"}, {"id"...   
1652  [{"id": 3436, "name": "karate"}, {"id": 9715, ...   
419   [{"id": 704, "name": "adolescence"}, {"id": 81...   
420   [{"id": 2096, "name": "auction"}, {"id": 7005,...   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
3494  Mark Singer returns as Dar, the warrior who ca...   
813   Mild-mannered Clark Kent works as a reporter a...   
870   Three escaped criminals from the planet Krypto...   
46    The ultimate X-Men ensemble fights a war for t...   
14    A young boy learns that he has extraordinary p...   
1296  Aiming to defeat the Man of Steel, wealthy exe...   
1652  The young warrior Son Goku sets out on a quest...   
419   David Rice is a man who knows no boundaries, a...   
420   In this continuation to the adventure of the d...   

                                         genres_literal  
0              Action Adventure Fantasy Science Fiction  
3494           Action Adventure Fantasy Science Fiction  
813            Action Adventure Fantasy Science Fiction  
870            Action Adventure Fantasy Science Fiction  
46             Action Adventure Fantasy Science Fiction  
14             Action Adventure Fantasy Science Fiction  
1296    Comedy Action Adventure Fantasy Science Fiction  
1652  Action Adventure Fantasy Science Fiction Thriller  
419                   Adventure Fantasy Science Fiction  
420                   Adventure Fantasy Science Fiction

In [165]:
# 8.1 Quiz

# 영화 이름을 검색하면 10개의 추천 영화 제목과 평점을 출력하도록 코딩하시오
# 힌트 : reshape 함수를 활용하세요


In [177]:
# 영화 이름을 입력 받으면 index 정보 찾기

movie_name = 'avatar'
title_movie = df_movies[df_movies['title'].str.lower().isin([movie_name.lower()])]
title_movie

movie_index = title_movie.index.values
movie_index
# index 정보를 이용하여 top10

movie_top10 = genre_similarity_sorted_idx[movie_index, :10]
print(type(movie_top10))

print(movie_top10)

<class 'numpy.ndarray'>
[[   0 3494  813  870   46   14 1296 1652  419  420]]


In [180]:

print(movie_top10.ndim, '차원 : ', movie_top10)
movie_top10 = movie_top10.reshape(-1)
# reshape(-1)  -1 가변적으로 만들겠다


2 차원 :  [[   0 3494  813  870   46   14 1296 1652  419  420]]


In [182]:
print(movie_top10.ndim, '차원 : ', movie_top10)
# top10 정보를 이용하여 영화 제목, 평점 추출
df_movies.iloc[movie_top10]
# df_movies.iloc[[   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420]]

1 차원 :  [   0 3494  813  870   46   14 1296 1652  419  420]


id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   
14     49521                               Man of Steel   
1296    9531                               Superman III   
1652   14164                       Dragonball Evolution   
419     8247                                     Jumper   
420    11253                Hellboy II: The Golden Army   

                                                 genres  vote_average  \
0         [Action, Adventure, Fantasy, Science Fiction]           7.2   
3494      [Action, Adventure, Fantasy, Science Fiction]           4.6   
813       [Action, Adventure, Fantasy, Science Fiction]           6.9   
870       [Action, Adventure, Fantasy, Science Fiction]           6.5   
46        [Action, Adventure, Fantasy, Science Fiction]           7.5   
14        [Action, Adventure, Fantasy, Science Fiction]           6.5   
1296  [Comedy, Action, Adventure, Fantasy, Science F...           5.3   
1652  [Action, Adventure, Fantasy, Science Fiction, ...           2.9   
419               [Adventure, Fantasy, Science Fiction]           5.9   
420               [Adventure, Fantasy, Science Fiction]           6.5   

      vote_count  popularity  \
0          11800  150.437577   
3494          17    1.478505   
813         1022   48.507081   
870          629   30.515175   
46          6032  118.078691   
14          6359   99.398009   
1296         490   22.164202   
1652         462   21.677732   
419         1799   21.218000   
420         1527   58.579760   

                                               keywords  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...   
3494  [{"id": 818, "name": "based on novel"}, {"id":...   
813   [{"id": 83, "name": "saving the world"}, {"id"...   
870   [{"id": 83, "name": "saving the world"}, {"id"...   
46    [{"id": 1228, "name": "1970s"}, {"id": 1852, "...   
14    [{"id": 83, "name": "saving the world"}, {"id"...   
1296  [{"id": 83, "name": "saving the world"}, {"id"...   
1652  [{"id": 3436, "name": "karate"}, {"id": 9715, ...   
419   [{"id": 704, "name": "adolescence"}, {"id": 81...   
420   [{"id": 2096, "name": "auction"}, {"id": 7005,...   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
3494  Mark Singer returns as Dar, the warrior who ca...   
813   Mild-mannered Clark Kent works as a reporter a...   
870   Three escaped criminals from the planet Krypto...   
46    The ultimate X-Men ensemble fights a war for t...   
14    A young boy learns that he has extraordinary p...   
1296  Aiming to defeat the Man of Steel, wealthy exe...   
1652  The young warrior Son Goku sets out on a quest...   
419   David Rice is a man who knows no boundaries, a...   
420   In this continuation to the adventure of the d...   

                                         genres_literal  
0              Action Adventure Fantasy Science Fiction  
3494           Action Adventure Fantasy Science Fiction  
813            Action Adventure Fantasy Science Fiction  
870            Action Adventure Fantasy Science Fiction  
46             Action Adventure Fantasy Science Fiction  
14             Action Adventure Fantasy Science Fiction  
1296    Comedy Action Adventure Fantasy Science Fiction  
1652  Action Adventure Fantasy Science Fiction Thriller  
419                   Adventure Fantasy Science Fiction  
420                   Adventure Fantasy Science Fiction

In [183]:
# ndim은 배열의 차원을 나타내는 객체이다. 
# 현재 movie_top10의 차원을 알아 보기 위해 ndim을 사용하였다.

# reshape 함수는 차원을 변경하기 위한 함수로 -1을 입력하게 되면 
# 그 차원은 자동으로 설정하게 되며 현재는 -1만 입력되어 1차원으로 설정되게 된다.

# top 10의 정보가 이차원 리스트 정보로 나타남으로 iloc에서 에러가 발생된다. 
# 이를 해결하기 위해 reshape함수를 이용하여 일차원 리스트로 변경하고 top10의 값을 추출할 수 있다.

In [188]:
df_movie_top10 = df_movies.iloc[movie_top10]
df_movie_top10[['title', 'vote_average']]

title  vote_average
0                                        Avatar           7.2
3494  Beastmaster 2: Through the Portal of Time           4.6
813                                    Superman           6.9
870                                 Superman II           6.5
46                   X-Men: Days of Future Past           7.5
14                                 Man of Steel           6.5
1296                               Superman III           5.3
1652                       Dragonball Evolution           2.9
419                                      Jumper           5.9
420                 Hellboy II: The Golden Army           6.5

In [185]:
# 위와 같이 입력된 영화에 따른 top10의 영화를 추천해 줄 수 있다.

In [189]:
df_movies[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [190]:
# 위에서 보듯이 평점이 좋지만 투표수가 적은 경우의 영화를 추천하기에는 문제가 있다. 
# 따라서 가중치를 이용한 추천 시스템을 구축할 것이다. 
# 다음은 유명한 영화 평점 사이트인 IMDB에서 사용한 공식이다.

# 가중 평점 = (v/(v+m)) * R + (m/(v+m)) * C
# v : 개별 영화에 평점을 투표한 횟수
# m : 평점을 부여하기 위한 최소 투표 횟수
# R : 개별 영화에 대한 평균 평점
# C : 전체 영화에 대한 평균 평점

In [196]:
#전체 영화에 대한 평균 평점
C = df_movies['vote_average'].mean()

#평점을 부여하기 위한 최소 투표 횟수
m = df_movies['vote_count'].quantile(0.6)
print('C : ', round(C, 3))
print('m : ', round(m, 3))


C :  6.092
m :  370.2


In [199]:
# 개별 영화에 평점을 투표한 횟수
v = df_movies['vote_count']

# 개별 영화에 대한 평균 평점
R = df_movies['vote_average']

(v/(v+m)) * R + (m/(v+m)) * C

0       7.166301
1       6.838594
2       6.284091
3       7.541095
4       6.098838
          ...   
4798    6.290894
4799    6.089611
4800    6.106650
4801    6.084894
4802    6.100782
Length: 4803, dtype: float64

In [200]:
# > 공식을 이용하여 각 영화들의 가중치 평점을 구했다.

In [201]:
df_movies['weighted_vote'] = (v/(v+m)) * R + (m/(v+m)) * C
df_movies[['title', 'vote_average','weighted_vote', 'vote_count']].sort_values('vote_average', ascending=False)[:10]

<ipython-input-201-43d5bd9a17cc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['weighted_vote'] = (v/(v+m)) * R + (m/(v+m)) * C


title  vote_average  weighted_vote  vote_count
3519          Stiff Upper Lips          10.0       6.102699           1
4247     Me You and Five Bucks          10.0       6.113170           2
4045     Dancer, Texas Pop. 81          10.0       6.102699           1
4662            Little Big Top          10.0       6.102699           1
3992                 Sardaarji           9.5       6.110483           2
2386            One Man's Hero           9.3       6.109409           2
2970        There Goes My Baby           8.5       6.105110           2
1881  The Shawshank Redemption           8.5       8.396052        8205
2796     The Prisoner of Zenda           8.4       6.158767          11
3337             The Godfather           8.4       8.263591        5893

In [202]:
# 실행 결과 투표수가 적은 영화는 가중치 평점이 낮았으며 투표수가 많은 영화일 수록 실 평점과 비슷한 수준으로 가중치 평점이 나타났다. 이를 이용하여 영화를 추천해 보자

In [203]:
#  Quiz

# 가중치 평균을 이용하여 상위 10개의 영화를 추천하는 프로그램을 만드시오.