In [1]:
import pandas as pd
# 판다스를 임포트해주고 앞으로 판다스를 PD로 부른다..

In [3]:
names = ['Bob','Jessica','Mary','John', 'Mel']
births = [968, 155, 77, 578, 973]
coutom = [1, 5, 25, 13, 23232]

In [5]:
BabyDataSet = list(zip(names,births))
df = pd.DataFrame(data = BabyDataSet, columns=['Names','Births'])

In [7]:
df.head()

Names  Births
0      Bob     968
1  Jessica     155
2     Mary      77
3     John     578
4      Mel     973

In [8]:
# 판다스는 행과열로 보여지게끔 만들어주는 데이터

In [9]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
print(df.columns)

Index(['Names', 'Births'], dtype='object')


In [12]:
# 데이터프레임의 하나의 열을 선택합니다.
# 나는 이름만 보고싶을 때
df['Names']

0        Bob
1    Jessica
2       Mary
3       John
4        Mel
Name: Names, dtype: object

In [13]:
# 데이터프레임의 하나의 행을 보고 싶다
# 인덱스를 지정한다.

df[0:3]

Names  Births
0      Bob     968
1  Jessica     155
2     Mary      77

In [15]:
# Births 열에서 100 보다 큰 데이터만 보고 싶을 때
df[df['Births'] > 100]

Names  Births
0      Bob     968
1  Jessica     155
3     John     578
4      Mel     973

In [16]:
# 데이터 프레임의 평균값 구하기
df.mean()

Births    550.2
dtype: float64

In [17]:
# describe 요약통계
df.describe()

Births
count    5.000000
mean   550.200000
std    428.424672
min     77.000000
25%    155.000000
50%    578.000000
75%    968.000000
max    973.000000

In [18]:
# 2. Numpy

In [4]:
import numpy as np

In [5]:
arr1 = np.arange(15).reshape(3,5)
print(arr1)

#reshape 는 행 열 구조로 뿌려줌

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
python_array = [0, 1, 2, 3, 4, 5 ,6]
np.array(python_array)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
# shape 는 행열의 구조를 알려줌
arr1.shape

(3, 5)

In [12]:
# zeros , ones 함수는 0 과 1로 된 데이터를 분석할 때 씀

arr3 = np.zeros((3,4))
arr4 = np.ones((3,4))

print(arr3)
print()
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# 넘피(numpy)를 쓰는 이유는 벡터나 행렬 연산을 위한 라이브러리