In [2]:
# Numpy
# 넘피는 벡터나 행열 연산을 하기 위해 사용

In [3]:
# numpy를 import 하고 np 라고 부른다
 
import numpy as np

In [4]:
# reshape 는 행 열 구조로 뿌려줌

arr1 = np.arange(15).reshape(3,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
python_arry = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(python_arry)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
np.array(python_arry)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# shape 는 행열의 구조를 알려줌

arr1.shape

(3, 5)

In [11]:
# zeros, ones 함수는 0 과 1로 된 데이터를 분석할 때 사용

arr3 = np.zeros((3,4))
arr4 = np.ones((3,4))

print(arr3)
print()
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
